using System.Reflection;
using System.Runtime.InteropServices;

// WARNING: If this file is named AssemblyInfo.cs, then it is autogenerated!
//
// Please edit tokenized/AssemblyInfo.cs.in.

[assembly: AssemblyTitle("RabbitMQ.ServiceModel")]
[assembly: AssemblyDescription("RabbitMQ Binding for Windows Communication Foundation")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Pivotal Software, Inc.")]
[assembly: AssemblyProduct("RabbitMQ")]
[assembly: AssemblyCopyright("Copyright © 2007-2016 Pivotal Software, Inc.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: Guid("95491647-ae2a-4332-b941-da3c101b3437")]

// We don't provide an AssemblyFileVersion, which (according to MSDN)
// means that AssemblyVersion will be used for the Win32 file version.
[assembly: AssemblyVersion("0.0.0.0")]
